[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  identifier = "projects"
  name = "Projecten"
  pageRef = "projects"
  weight = 20

[[main]]
  identifier = "resume"
  name = "CV"
  url = "/resume.pdf"
  weight = 30
