[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 20

[[main]]
  identifier = "resume"
  name = "Resume"
  url = "/resume.pdf"
  weight = 30
